byCedric/expo-monorepo-example

.github/workflows/standalone.yml
packages/app/eas.json
packages/app/package.json

This integrates EAS tooling into our monorepo.

chore: configure app to work with eas

---

.github/workflows/standalone.yml
packages/app/.gitignore
packages/app/eas.json
packages/app/index.js
packages/app/package.json
yarn.lock

This fixes the missing package links to `packages/app` for Android.

fix: add missing symlinks for native packages

---

.github/workflows/standalone.yml
apps/ejected/app.json
apps/ejected/eas.json
apps/ejected/ios/easmonorepoexample.xcodeproj/project.pbxproj
apps/managed/app.json
apps/managed/eas.json

Add iOS builds to the example apps.

feature: add support for ios builds

---

.github/workflows/standalone.yml
README.md

Never liked it, but had to do it bc of issues with my dev certificate. It's solved now.

chore: remove local ios certificates

---

apps/managed/eas.json

refactor: upgrade eas configuration and rename build profiles

---

.github/workflows/preview.yml
.github/workflows/standalone.yml
.github/workflows/test.yml
apps/managed/App.tsx

Updating the workflows to the latest GH action, with some clean-ups.

chore: update the preview workflow with latest action

---

apps/ejected/package.json
apps/managed/package.json
apps/with-dev-client/package.json
apps/with-sentry/package.json
yarn.lock

Bumping react native to 0.64.3

chore: upgrade react native to 0.64.3

---

apps/managed/App.tsx

Accidentally merged this one, should also be good to test out the comment stuff :)

chore(apps/managed): rollback test message

---

.prettierrc
apps/ejected/App.tsx
apps/ejected/babel.config.js
apps/ejected/index.js
apps/ejected/metro.config.js
apps/ejected/tsconfig.json
apps/managed/App.tsx
apps/managed/babel.config.js
apps/managed/index.js
apps/managed/metro.config.js
apps/managed/tsconfig.json
apps/with-dev-client/App.tsx
apps/with-dev-client/babel.config.js
apps/with-dev-client/hooks.ts
apps/with-dev-client/index.js
apps/with-dev-client/metro.config.js
apps/with-dev-client/react-native-mmkv-plugin.js
apps/with-dev-client/react-native.config.js
apps/with-dev-client/tsconfig.json
apps/with-sentry/App.tsx
apps/with-sentry/babel.config.js
apps/with-sentry/index.js
apps/with-sentry/metro.config.js
apps/with-sentry/tsconfig.json
packages/eslint/package.json
packages/ui/src/index.tsx
packages/ui/tsconfig.json
tsconfig.shared.json
yarn.lock

Follow up of https://github.com/byCedric/eas-monorepo-example/pull/23#issuecomment-950398805

chore: upgrade linting to support latest typescript

---

apps/ejected/metro.config.js
apps/managed/metro.config.js
apps/with-dev-client/metro.config.js
apps/with-sentry/metro.config.js

Fixes #47 .
See additional context in the linked issue :arrow_up: .

fix: nodeModulesPaths typo in metro config

---

.github/actions/setup-monorepo/action.yml
.github/workflows/preview.yml
.github/workflows/standalone.yml
.github/workflows/test.yml
README.md

Helps clean up the workflows and is easier to maintain.

refactor: use composite action for all workflows

---

.github/workflows/test.yml
packages/feature-home/babel.config.js
packages/feature-home/package.json
packages/feature-home/src/__tests__/HomeIcon.test.tsx
packages/feature-home/src/__tests__/HomeScreen.test.tsx
packages/ui/babel.config.js
packages/ui/package.json
packages/ui/src/__tests__/Paragraph.test.tsx
packages/ui/src/__tests__/Strong.test.tsx
pnpm-lock.yaml

Adds basic unit tests for the packages.

feature: add tests for packages

---

README.md

Update readme with new badges and links.

docs: update readme with new badges and links

---

package.json
pnpm-lock.yaml

refactor: upgrade turborepo to 1.5.1

---

.prettierrc
package.json

Skip those files as much as we can.

refactor: drop prettier config file

---

apps/mobile/package.json
package.json
packages/eslint-config/package.json
packages/eslint-config/patches/eslint-config-universe@11.1.1.patch
packages/feature-home/package.json
packages/ui/package.json
pnpm-lock.yaml

Just a maintenance update, switching over to Expo SDK 47.

refactor: upgrade to Expo sdk 47

---

README.md

docs: fix packages/eslint-config link in readme

---

README.md

I had this thing in my head for way too long, glad I finally could put it on paper.

docs: add more context about this repository

---

.github/actions/setup-monorepo/action.yml
.github/workflows/preview.yml
apps/mobile/app.json

chore: use latest expo-github-action for EAS update previews

---

packages/feature-home/package.json
pnpm-lock.yaml

chore(home): drop bob

---

packages/feature-home/package.json
pnpm-lock.yaml

fix(feature-home): add missing tsup as dev dependency

---

README.md

Fixed in: https://github.com/facebook/react-native/commit/4a4cceef2570c2a68ae91db0648aaaf08cf6c426

docs: remove the code signing monorepo issue

---

.github/actions/setup-monorepo/action.yml
apps/mobile/eas.json
apps/mobile/package.json
apps/web/package.json
package.json
packages/eslint-config/package.json
packages/feature-home/package.json
packages/ui/package.json
pnpm-lock.yaml

Another release, another update.

refactor: upgrade to expo sdk 49

---

apps/mobile/package.json

There is reported issue that causing crash ios app on local simulator
* https://github.com/expo/expo/issues/23382
No particularly

fix: crash ios amulator

---

apps/mobile/package.json
pnpm-lock.yaml

fix(mobile): update lockfile and use `expo@49.0.10`

---

apps/mobile/package.json
packages/feature-home/package.json
packages/ui/package.json
pnpm-lock.yaml

refactor: update to `@types/react@18.2.43`

---

apps/example/package.json
package.json
packages/feature-home/package.json
packages/ui/package.json
pnpm-lock.yaml

chore: update dependencies to latest versions within range

---

pnpm-workspace.yaml

chore: minimumReleaseAge to `pnpm-workspace.yaml`
